In [1]:
import pandas as pd, numpy as np

In [2]:
## Import raw data

df_red = pd.read_csv('winequality-red.csv', sep = ';')
df_white = pd.read_csv('winequality-white.csv', sep = ';')

In [3]:
## Check length of raw data

df_red['wine'] = 'red'
df_red.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
 12  wine                  1599 non-null   object
dtypes: float64(11), int64(1), object(1)
memory usage: 162.5+ KB

In [4]:
## Check length of raw data

df_white['wine'] = 'white'
df_white.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
 12  wine                  4898 non-null   object
dtypes: float64(11), int64(1), object(1)
memory usage: 497.6+ KB

In [5]:
## Merging data frames
wine_quality = pd.concat([df_red, df_white])

## Removing White wine outliers
wine_quality = wine_quality.loc[wine_quality['density'] < 1.004, ]

## Adding final relative quality column
wine_quality['quality_factor'] = wine_quality['quality'].apply(lambda x: 'Below Average' if x < 6 
                                                               else ('Above Average' if x > 6 else 'Average'))

## Reorganizing columns
cols = ['wine','fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol','quality','quality_factor']
wine_quality = wine_quality[cols]
wine_quality.columns = map(str.title, wine_quality.columns)
wine_quality = wine_quality.rename(columns={'Ph': 'pH'})

## Check length of new data (6497 = 4898 + 1599 )
wine_quality.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6494 entries, 0 to 4897
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Wine                  6494 non-null   object
 1   Fixed Acidity         6494 non-null   float64
 2   Volatile Acidity      6494 non-null   float64
 3   Citric Acid           6494 non-null   float64
 4   Residual Sugar        6494 non-null   float64
 5   Chlorides             6494 non-null   float64
 6   Free Sulfur Dioxide   6494 non-null   float64
 7   Total Sulfur Dioxide  6494 non-null   float64
 8   Density               6494 non-null   float64
 9   pH                    6494 non-null   float64
 10  Sulphates             6494 non-null   float64
 11  Alcohol               6494 non-null   float64
 12  Quality               6494 non-null   int64
 13  Quality_Factor        6494 non-null   object
dtypes: float64(11), int64(1), object(2)
memory usage: 761.0+ KB

In [6]:
## Last check on df structure
wine_quality.sample(8)

,Wine,Fixed Acidity,Volatile Acidity,Citric Acid,Residual Sugar,Chlorides,Free Sulfur Dioxide,Total Sulfur Dioxide,Density,pH,Sulphates,Alcohol,Quality,Quality_Factor
1061,white,7.0,0.21,0.28,7.5,0.070,45.0,185.0,0.99660,3.34,0.55,9.4,5,Below Average
550,red,6.8,0.51,0.01,2.1,0.074,9.0,25.0,0.99580,3.33,0.56,9.5,6,Average
4381,white,6.4,0.30,0.27,5.0,0.058,27.0,151.0,0.99198,3.22,0.49,12.2,6,Average
4878,white,6.2,0.53,0.02,0.9,0.035,6.0,81.0,0.99234,3.24,0.35,9.5,4,Below Average
709,red,9.7,0.31,0.47,1.6,0.062,13.0,33.0,0.99830,3.27,0.66,10.0,6,Average
3245,white,7.6,0.27,0.29,2.5,0.059,37.0,115.0,0.99328,3.09,0.37,9.8,5,Below Average
852,white,6.9,0.18,0.36,1.3,0.036,40.0,117.0,0.99340,3.27,0.95,9.5,7,Above Average
2508,white,6.6,0.26,0.25,11.6,0.045,45.0,178.0,0.99691,3.33,0.43,9.8,6,Average

In [7]:
## Export
wine_quality.to_csv('wine_quality.csv', index=False)

In [8]:
## Test import
pd.read_csv('wine_quality.csv')

,Wine,Fixed Acidity,Volatile Acidity,Citric Acid,Residual Sugar,Chlorides,Free Sulfur Dioxide,Total Sulfur Dioxide,Density,pH,Sulphates,Alcohol,Quality,Quality_Factor
0,red,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,Below Average
1,red,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,Below Average
2,red,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,Below Average
3,red,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,Average
4,red,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,Below Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6489,white,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,Average
6490,white,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,Below Average
6491,white,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,Average
6492,white,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,Above Average
6493,white,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,Average